export const links = {
  home: 'https://injective.com',
  explorerInj: 'https://explorer.injective.network',
  explorerInEvm: 'https://inevm.calderaexplorer.xyz',
  explorer: 'https://explorer.hyperlane.xyz',
  docs: 'https://docs.hyperlane.xyz',
  about: 'https://www.hyperlane.xyz',
  support: 'https://discord.gg/hyperlane',
  gasDocs: 'https://docs.hyperlane.xyz/docs/reference/hooks/interchain-gas',
  chains: 'https://docs.hyperlane.xyz/docs/resources/domains',
  discord: 'https://discord.gg/hyperlane',
  github: 'https://github.com/hyperlane-xyz/hyperlane-warp-ui-template',
  twitter: 'https://twitter.com/hyperlane',
  blog: 'https://medium.com/hyperlane',
  caldera: 'https://www.caldera.xyz',
};
