export const links = {
  home: 'https://injective.com',
  explorerInj: 'https://explorer.injective.network',
  explorerInEvm: 'https://inevm.calderaexplorer.xyz',
  explorer: 'https://explorer.hyperlane.xyz',
  docs: 'https://docs.hyperlane.xyz',
  about: 'https://www.hyperlane.xyz',
  support: 'https://discord.gg/hyperlane',
  warpDocs: 'https://docs.hyperlane.xyz/docs/reference/applications/warp-routes',
  gasDocs: 'https://docs.hyperlane.xyz/docs/reference/hooks/interchain-gas',
  chains: 'https://docs.hyperlane.xyz/docs/resources/domains',
  discord: 'https://discord.gg/hyperlane',
  github: 'https://github.com/hyperlane-xyz/hyperlane-warp-ui-template',
  twitter: 'https://twitter.com/hyperlane',
  blog: 'https://medium.com/hyperlane',
  caldera: 'https://www.caldera.xyz',
  tos: 'https://hyperlane.xyz/terms-of-service',
  privacyPolicy: 'https://hyperlane.xyz/privacy-policy',
  bounty:
    'https://github.com/search?q=org:hyperlane-xyz+label:bounty+is:open+is:issue&type=issues&s=&o=desc',
};
